### ISSUE TITLE
Add custom fonts to the web page

### ISSUE THREAD

**Issue by richterich** [richterich/richterich#12]
Currently custom fonts are **not recognized** if they are not installed on a local machine. Add both `Roboto` and `Roboto Mono` fonts to the web page. Include fonts in `ttf` and `otf` format in `fonts` directory and link them via css.

Example:

```css
@font-face {
    font-family: "FontName";
    src: url("fonts/FontName.ttf") format("truetype"),
             url("fonts/FontName.otf") format("opentype");
}
```
